### ISSUE TITLE
Add a monitoring-tool for DigitalOcean to Darknode installation script

### ISSUE THREAD

**Issue by antaeus1986** [renproject/darknode-cli#18]
When I deploy a Darknode in DigitalOcean, please will added to installation script, the DO-agent installation. To be able to get good performance graphs

Enable Monitoring on Droplet by installing the DO Agent 
curl -sSL https://agent.digitalocean.com/install.sh | sh

https://www.digitalocean.com/docs/monitoring/quickstart/

**Comment by tok-kkk** [comment]
Thanks, @antaeus1986 , we'll consider adding this in our next release.

**Comment by tok-kkk** [comment]
Close this as resolved by PR #36
