### ISSUE TITLE
darknode up fails for legacy AWS accounts in some regions

### ISSUE THREAD

**Issue by andrewbaine** [renproject/darknode-cli#3]
Old AWS Accounts may not have a default VPC in all regions. See 

https://aws.amazon.com/blogs/aws/amazon-ec2-update-virtual-private-clouds-for-everyone/
https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/default-vpc.html

I was able to work around by bringing a node up in a region I've never used before, however, I would like to run nodes in many regions including first and foremost us-east-1. There's no way to convert an account from classic to VPC-only, so I would need to create a new AWS account. Can you add a flag --aws-vpc-id and --aws-subnet-id so that users can specify what VPC to launch their instance into? This makes sense from a security perspective, too, since there might be other stuff running within default VPC which is not properly connected to darknodes.

**Comment by andrewbaine** [comment]
I won't be able to work around by creating a default VPC in "classic" regions:

```
$ aws ec2 create-default-vpc

An error occurred (OperationNotPermitted) when calling the CreateDefaultVpc operation: Accounts on the EC2-Classic platform cannot create a default VPC.
```

**Comment by loongy** [comment]
@tok-kkk this can easily be solved by adding the `--aws-vpc <vpc-id>` argument. If not specified, then it uses the default VPC for that region.

**Comment by andrewbaine** [comment]
Operators who specify a vpc id will also need to specify a subnet id
