### ISSUE TITLE
Does not work on Raspberry PI

### ISSUE THREAD

**Issue by antaeus1986** [renproject/darknode-cli#39]
I tried to install on Raspberry pi, but got an error:
`unsupported os type or architecture`

I used PI 3 and Ubuntu:
```
root@DarknodePi:~# uname -a
Linux DarknodePi 5.3.0-1008-raspi2 #9-Ubuntu SMP Fri Oct 18 13:26:35 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by tok-kkk** [comment]
Close this as `aarch64` support has been added in #41
