### ISSUE TITLE
Function "detailed monitoring" - does not always work

### ISSUE THREAD

**Issue by antaeus1986** [renproject/darknode-cli#40]
I use the Digital ocean, but monitoring is not always set with deploy the droplets. I asked my friend from the community, he has the same situation.

**Comment by tok-kkk** [comment]
Thanks @antaeus1986 for reporting this. We have changed the way how we enable detail monitoring on Digital Ocean #42. Nodes deployed on DO with the new version cli should have detail monitoring enabled. 
For previously deployed node, you can follow digital oceans's [instructions](https://www.digitalocean.com/docs/monitoring/quickstart/) to manually enable the monitoring.
