### ISSUE TITLE
Show darknode version 

### ISSUE THREAD

**Issue by tok-kkk** [renproject/darknode-cli#58]
# Object
- We want the CLI to be able to show the version of each darknode.
- (Optional)We want the CLI to be able to show if the darknode is running. We can show it from the command center or we can do it in both. 

# Design
## Status 
To check if a darknode is running, we can simply send a `queryStat` request to darknode and check the status code in the response. It's a bit heavy for the `list` command to check if the darknode is running properly(i.e progress in hyperdrive, participate in execution...). We might need a separate command for that or show these info from via the command centre. The output should be one of `Yes` or `No` or `N/A`(no internet connection)

## VERSION
Current darknode has an issue with its version system, so the CLI uses a `version` file inside the darknode instance (`~/.darknode/version`) to keep tracking its version. The version file is created when user runs the `up` command and successfully deploy a node. The version file will be set to the latest version number when created and will be updated when user runs the `update` command. 
If we want to implement this issue before the darknode version system gets fixed. We can always rely on the content of the `~/.darknode/version` file.
> Nothing we can do if user modifies the version manually. 

If we want to wait for a fix of the darknode version system, there are two ways we can get the version from darknode binary. 
1. Sending a `queryStat` request and extract the version from the response. This approach requires the darknode to be running. 
1. SSH into the darknode and run `~/.darknode/bin/darknode --version`. This approach requires the binary is valid and exists at expect location.

The (1) approach is faster than (2) and can get the status information from the same request.

# Implementation 
The implementation will depend on which approach we choose(or use both) and whether we want to show the status.  
Some things we must have. 
- Checks should be done in parallel and have a reasonable context. 
- If the implementation involves sending requests or ssh, it should handle situations when internet connection is disabled.

**Comment by loongy** [comment]
I think it definitely makes sense to add these details to the `darknode list` command, instead of adding new subcommands.

**Comment by tok-kkk** [comment]
Resolved in v3.0.10
