### ISSUE TITLE
Support -devnet and -testnet suffixes for release versions

### ISSUE THREAD

**Issue by loongy** [renproject/darknode-cli#61]
Currently, our versioning system does not differentiate between Devnet, Testnet, and Mainnet releases. This has been fine during internal development, but is very likely to cause issues when community members are managing their own Darknodes.

This issue proposes the `-devnet` and `-testnet` suffixes to versions. For example, running `darknode update 0.2.8-devnet4` would look at https://github.com/renproject/darknode-release for a release labelled `0.2.8-devnet4`, download it, and deploy it to the Darknode.

### Format

All versions must match the following regex: `[0-9]+\.[0-9]+\.[0-9]+(-(devnet|testnet)[0-9]+)?`.

### Rules

- Versions with no suffix are considered stable enough for Mainnet. Only commits that are merged into the `master` branch are allowed to be tagged for stable release.
- Versions with the `-testnet[0-9]+` suffix are considered to be *beta* releases that are stable enough for Testnet, but not Mainnet.
- Versions with the `-devnet[0-9]+` suffix are considered to be *alpha* releases that are not stable enough for Testnet, or Mainnet, but are stable enough for Devnet.
- Version `x.y.z` is greater than `x.y.z-testnet*` which is greater than `x.y.z-devnet*`. The suffix number determines ordering within the `-testnet` and `-devnet` for the same release version.

### Examples

- `0.2.8` is stable and usable on Mainnet.
- `0.3.0-testnet1` is the 1st release of `0.3.0` for Testnet
- `0.3.1-devnet4` is the 4th release of `0.3.1` for Devnet

### Tagging

Commits in https://github.com/renproject/darknode should be tagged with their release version. This should prompt GitHub Actions to automatically build it, and release it to the https://github.com/renproject/darknode-release repo.

Tagging will be done manually for now, but if this process is working well for the team then we can look into automate it.

**Comment by tok-kkk** [comment]
resolved in v3.0.10
