### ISSUE TITLE
How to add ETH to Darknode 

### ISSUE THREAD

**Issue by adamrayfo1** [renproject/darknode-cli#62]
Is there a way to add GAS via darknode-cli ???

Using Linux Terminal

**Comment by tok-kkk** [comment]
The darknode-cli is not a wallet tool and we have no plan to support that. You need to go to the [Command Center](https://docs.renproject.io/chaosnet/chaosnet-darknode/untitled-1/mac-os-and-linux) to add GAS for your darknode.

**Comment by adamrayfo1** [comment]
I cannot add ETH via the UI. 

Whenever I click on Deposit I receive a message that says "Unable to complete transaction: [Chaosnet-production] Invalid ETH amount - please try again" 

I wonder does this have anything to do with the fact that Ren VM hasn't released Mainnet yet. 

I was just watching an interview on Nuggetz News and Loong Wang was saying something about not wanting people to lose their money etc., 

I may be jumping the gun.

I knew I would have an initial waiting period for my darknode to be registered but now it's saying I am registered but it also gives a notification that I have a low gas balance and that the node won't earn fees if it runs out of ETH.
