### ISSUE TITLE
"cannot find any stable release" when deploying node

### ISSUE THREAD

**Issue by eljefeguero** [renproject/darknode-cli#79]
When trying to deploy node to digital ocean with cli version 3.0.12 the error "cannot find any stable release" is displayed

**Comment by tok-kkk** [comment]
Thanks for reporting that. I just tried locally and confirmed I can reproduce this. 
Will push a fix for this soon.

**Comment by eljefeguero** [comment]
awesome, thank you!

**Comment by tok-kkk** [comment]
I have release 3.0.13 which should fix your issue. 
Feel free to close this issue if the new release fixs it.

**Comment by eljefeguero** [comment]
fixed, team is second to none with ren!
