### ISSUE TITLE
Where can we configure IP+Port (SSH) the CLI is using for each darknode?

### ISSUE THREAD

**Issue by xtc0r** [renproject/darknode-cli#82]
How does the Darknode CLI figure out IP+ SSH port per darknode?
I need to change the SSH Port which the CLI is using as my (darknode) server is not using port 22 for SSH. I couldn't find it in the config.json.

**Comment by tok-kkk** [comment]
It's not supported at the moment. The CLI always uses the default port number for ssh. 
For now, you need to modify the source code and build the binary yourself to get that working.

**Comment by xtc0r** [comment]
Is this something on your roadmap or you think it's not important and will never be made configurable?

**Comment by tok-kkk** [comment]
It's not on our current roadmap.

**Comment by fanaticalfishing** [comment]
> It's not supported at the moment. The CLI always uses the default port number for ssh.
> For now, you need to modify the source code and build the binary yourself to get that working.

I would like to do this. Port 22 is getting a hammered by bots. Will this interfere with REN project traffic?
