### ISSUE TITLE
Help installing Darknode CLI- command not found

### ISSUE THREAD

**Issue by danidwarf** [renproject/darknode-cli#85]
I installed Darknode CLI 
`curl https://www.github.com/renproject/darknode-cli/releases/latest/download/install.sh -sSfL | sh`

and saw the green text
`export PATH=$PATH:$HOME/ .darknode/bin
Done! Restart terminal and run the command below to begin.
darknode up --help`

I opened new terminal and ran

`darknode --version`
`darknode up --help `

getting command not found: darknode

**Comment by loongy** [comment]
@danidwarf what OS and terminal are you using?

**Comment by danidwarf** [comment]
macOS Big Sur version 11.0.1
zsh

**Comment by tok-kkk** [comment]
Could you try running `export PATH=$PATH:$HOME/ .darknode/bin` which shows in the green text and then `darknode --version`? 
Usually this means the PATH is not correctly set up. It might be something with Big Sur as we haven't tested it on Big Sur.

**Comment by tok-kkk** [comment]
This should be fixed in the latest release.
