### ISSUE TITLE
getting error context deadline exceeded on deploy

### ISSUE THREAD

**Issue by ifelsellc** [renproject/darknode-cli#90]
When using darknode up to deploy a new darknode I'm getting the error "context deadline exceeded"
using ver 3.0.15

I'm using digital ocean and I've deployed a darknode before using the same api token
calling the command the same way as instructed https://docs.renproject.io/darknodes/getting-started/digital-ocean-or-how-to-setup-a-darknode/mac-os-and-linux with my own values.

darknode up --name mynode --do --do-token myapitoken

**Comment by winson-procore** [comment]
Looks like this was a Digital Ocean problem. The problem fixed itself after trying this again 3 hrs later.

**Comment by tok-kkk** [comment]
Thanks for reporting this.  We'll add more details to the error message in the next upgrade.
