### ISSUE TITLE
access darknode ui from a different client machine

### ISSUE THREAD

**Issue by gWOLF3** [renproject/darknode-cli#93]
how do i access my darknode from a different client machine than the one i used to create it; in other words, how to connect darknode cli on other client to preexisting darknode?

i still have access to cloud server and api key. 

basically, i would like to separate out server management and custody.

thanks.

**Comment by tok-kkk** [comment]
@gWOLF3 To access your darknodes from another, you can 
1. Install `darknode-cli` on the new machine
2. Copy over the folder `/Users/<user>/.darknode/darknodes` from your old machine to the new one.
3. You should be able to see your darknodes from the new machine by running `darknode list`
