### ISSUE TITLE
Rate Limiting of api.github.com requests

### ISSUE THREAD

**Issue by andrewbaine** [renproject/darknode-cli#94]
`darknode up` hits a rate limited github API; I would like to be able to do 

```
export GITHUB_TOKEN=${my_secret_github_token}
```

and have the CLI use this token if present in the environment so that I get the benefit of a higher rate limit.

```
$ darknode up --do --do-token ${TOKEN} --do-region $REGION --name ${NAME}
GET https://api.github.com/repos/renproject/darknode-release/releases?per_page=25:
403 API rate limit exceeded for REDACTED.
(But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
[rate reset in 5m46s]
```

It looks like by convention this token is called `GITHUB_TOKEN`, [see github docs](https://docs.github.com/en/actions/security-guides/automatic-token-authentication)

**Comment by tok-kkk** [comment]
Closing this since it is now available in 3.1.0 release.
