### ISSUE TITLE
sh: 150: Syntax error

### ISSUE THREAD

**Issue by wipeoutxxx** [renproject/darknode-cli#97]
The command "curl https://www.github.com/renproject/darknode-cli/releases/latest/download/update.sh -sSfL | sh" to update the darknode CLI (3.0.15 → 3.1.0) I entered, but the error "sh: 150: Syntax error:" ("Unexpected (requires"} ")" is displayed and the CLI cannot be updated.　I'm an amateur so I don't have any programming skills.
Please tell me how to resolve.

**Comment by tok-kkk** [comment]
Hi @wipeoutxxx, we are aware of this issue and working on a fix for this. 
For now, you can use
```shell
curl https://www.github.com/renproject/darknode-cli/releases/latest/download/update.sh -sSfL | bash
```
to upgrade your darknode-cli

**Comment by wipeoutxxx** [comment]
I was able to upgrade the CLI. Thank you very much.
